repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.259'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/dead
    rev: v1.5.0
    hooks:
      - id: dead
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.2
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, postgres]
        # For dbt projects, this installs the dbt "extras".
        # You will need to select the relevant dbt adapter for your dialect
        # (https://docs.getdbt.com/docs/available-adapters):
        # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        args: [--dialect, postgres]
        # Arbitrary arguments to show an example
        # args: [--rules, "L003,L014"]
        # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
